/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zju_openeye_MainActivity */

#ifndef _Included_com_zju_openeye_MainActivity
#define _Included_com_zju_openeye_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zju_openeye_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zju_openeye_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_zju_openeye_MainActivity
 * Method:    myNativeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zju_openeye_MainActivity_myNativeString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
